version: "3.9"  
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      REDISHOST: redis:6379
  redis:
    image: redis
    ports:
      - "6379:6379"